font:
  normal:
    family: JetBrains Mono
    style: Regular

  bold:
    family: JetBrains Mono
    style: Bold

  italic:
    family: JetBrains Mono
    style: Italic

  size: 12.0

  offset:
    x: 0
    y: 8

  glyph_offset:
    x: 0
    y: 4

selection:
  save_to_clipboard: true

  #background_opacity: 0.9

window:
  padding:
    x: 10
    y: 10

draw_bold_text_with_bright_colors: true

colors:
  # Default colors
  primary:
    background: "#2E3440"
    foreground: "#D8DEE9"

  # Normal colors
  normal:
    black: "#3B4252"
    red: "#BF616A"
    green: "#A3BE8C"
    yellow: "#EBCB8B"
    blue: "#81A1C1"
    magenta: "#B48EAD"
    cyan: "#88C0D0"
    white: "#E5E9F0"

  # Bright colors
  bright:
    black: "#4C566A"
    red: "#BF616A"
    green: "#A3BE8C"
    yellow: "#EBCB8B"
    blue: "#81A1C1"
    magenta: "#B48EAD"
    cyan: "#8FBCBB"
    white: "#ECEFF4"
